---
image:
  name: ansible-lint:jupiter-custom
  entrypoint: [""]

stages:
  - test - syntax and code quality
  - test - critical automations
  # - review - Merge review is done by GitLab merge approval, only when the pipeline succeeds
  - deploy

lint ansible playbooks:
  stage: test - syntax and code quality
  script:
    - ansible-lint -p .
  only:
    - merge_requests

test critical automation:
  stage: test - critical automations
  variables:
    ANSIBLE_TOKEN: $ANSIBLE_TOKEN
    ANSIBLE_HOST: $ANSIBLE_HOST
  script:
    - python /tester.py 'tester/critical_automations.yml'
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "production"
      - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "pre_production"



.deploy: &deploy
  stage: deploy
  script:
    - 'curl -X GET -H "Authorization: Bearer ${ANSIBLE_TOKEN}" ${ANSIBLE_HOST}/api/v2/projects/${PROJECT_ID}/update/ -k |grep "{\"can_update\":true}"'

Deploy Testing:
  <<: *deploy
  variables:
    ANSIBLE_TOKEN: $ANSIBLE_TOKEN
    ANSIBLE_HOST: $ANSIBLE_HOST
    PROJECT_ID: 134
  only:
    - testing

Deploy Pre-Production:
  <<: *deploy
  variables:
    ANSIBLE_TOKEN: $ANSIBLE_TOKEN
    ANSIBLE_HOST: $ANSIBLE_HOST
    PROJECT_ID: 135
  only:
    - pre_production

Deploy Production:
  <<: *deploy
  variables:
    ANSIBLE_TOKEN: $ANSIBLE_TOKEN
    ANSIBLE_HOST: $ANSIBLE_HOST
    PROJECT_ID: 87
  only:
    - production
