---
image:
  name: ansible-lint:mars-custom
  entrypoint: [""]

stages:
  - test - syntax and code quality
  - test - critical automations
  # - review - Merge review is done by GitLab merge approval, only when the pipeline succeeds
  - deploy

# lint ansible playbooks:
#   stage: test - syntax and code quality
#   script:
#     - ansible-lint -p .

# test critical automation:
#   stage: test - critical automations
#   variables:
#     ANSIBLE_TOKEN: $ANSIBLE_TOKEN
#     ANSIBLE_HOST: $ANSIBLE_HOST
#   script:
#     - python /tester.py 'tester/tester.yaml'

.deploy: &deploy
  stage: deploy
  script:
    - echo $ANSIBLE_HOST
    - 'curl -X GET -H "Authorization: Bearer ${ANSIBLE_TOKEN}" https://${ANSIBLE_HOST}/api/v2/projects/${PROJECT_ID}/update/ -k'

Deploy Master:
  <<: *deploy
  variables:
    ANSIBLE_TOKEN: $ANSIBLE_TOKEN
    ANSIBLE_HOST: $ANSIBLE_HOST
    PROJECT_ID: 87
  only:
    - master

Deploy Pre-Production:
  <<: *deploy
  variables:
    ANSIBLE_TOKEN: $ANSIBLE_TOKEN
    ANSIBLE_HOST: $ANSIBLE_HOST
    PROJECT_ID: --TBD--
  only:
    - pre_production

Deploy Production:
  <<: *deploy
  variables:
    ANSIBLE_TOKEN: $ANSIBLE_TOKEN
    ANSIBLE_HOST: $ANSIBLE_HOST
    PROJECT_ID: --TBD--
  only:
    - production
