---
image:
  name: ansible-lint:mars-custom
  entrypoint: [""]

stages:
  - test - syntax and code quality
  - test - critical automations
  - review
  - deploy

lint ansible playbooks:
  stage: test - syntax and code quality
  script:
    - ansible-lint -p .

test critical automation:
  stage: test - critical automations
  variables:
    ANSIBLE_TOKEN: $ANSIBLE_TOKEN
    ANSIBLE_HOST: $ANSIBLE_HOST
  script:
    - python /tester.py 'tester.yaml'
