---
image:
  name: ansible-lint:mars-custom
  entrypoint: [""]

stages:
  - test - syntax and code quality
  - test - critical automations
  # - review - Merge review is done by GitLab merge approval, only when the pipeline succeeds
  - deploy

lint ansible playbooks:
  stage: test - syntax and code quality
  script:
    - ansible-lint -p .

test critical automation:
  stage: test - critical automations
  variables:
    ANSIBLE_TOKEN: $ANSIBLE_TOKEN
    ANSIBLE_HOST: $ANSIBLE_HOST
  script:
    - python /tester.py 'tester/tester.yaml'

deploy:
  stage: deploy
  variables:
    ANSIBLE_TOKEN: $ANSIBLE_TOKEN
  script:
    - 'curl -X GET -H "Authorization: Bearer $ANSIBLE_TOKEN" https://ansible.apps.mars/api/v2/projects/87/update/ -k'
  

