---
- name: Azure VM power off and power on
  hosts: localhost
  gather_facts: false
  vars:
    vm_name:
    resource_group:
    action_to_take:
  tasks:
    - name: Power Off
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        started: false
      when: action_to_take == 'poweroff'

    - name: Power On
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        started: true
      when: action_to_take == 'poweron'
